// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example2.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExampleTwoRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleTwoRequest) Reset()         { *m = ExampleTwoRequest{} }
func (m *ExampleTwoRequest) String() string { return proto.CompactTextString(m) }
func (*ExampleTwoRequest) ProtoMessage()    {}
func (*ExampleTwoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a28440b8a26ff835, []int{0}
}

func (m *ExampleTwoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleTwoRequest.Unmarshal(m, b)
}
func (m *ExampleTwoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleTwoRequest.Marshal(b, m, deterministic)
}
func (m *ExampleTwoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleTwoRequest.Merge(m, src)
}
func (m *ExampleTwoRequest) XXX_Size() int {
	return xxx_messageInfo_ExampleTwoRequest.Size(m)
}
func (m *ExampleTwoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleTwoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleTwoRequest proto.InternalMessageInfo

func (m *ExampleTwoRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ExampleTwoResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleTwoResponse) Reset()         { *m = ExampleTwoResponse{} }
func (m *ExampleTwoResponse) String() string { return proto.CompactTextString(m) }
func (*ExampleTwoResponse) ProtoMessage()    {}
func (*ExampleTwoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a28440b8a26ff835, []int{1}
}

func (m *ExampleTwoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleTwoResponse.Unmarshal(m, b)
}
func (m *ExampleTwoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleTwoResponse.Marshal(b, m, deterministic)
}
func (m *ExampleTwoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleTwoResponse.Merge(m, src)
}
func (m *ExampleTwoResponse) XXX_Size() int {
	return xxx_messageInfo_ExampleTwoResponse.Size(m)
}
func (m *ExampleTwoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleTwoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleTwoResponse proto.InternalMessageInfo

func (m *ExampleTwoResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExampleTwoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ExampleTwoRequest)(nil), "s12.example.ExampleTwoRequest")
	proto.RegisterType((*ExampleTwoResponse)(nil), "s12.example.ExampleTwoResponse")
}

func init() { proto.RegisterFile("example2.proto", fileDescriptor_a28440b8a26ff835) }

var fileDescriptor_a28440b8a26ff835 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0x35, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2e, 0x36, 0x34, 0xd2,
	0x83, 0x8a, 0x29, 0x29, 0x73, 0x09, 0xba, 0x42, 0x98, 0x21, 0xe5, 0xf9, 0x41, 0xa9, 0x85, 0xa5,
	0xa9, 0xc5, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41,
	0x4c, 0x99, 0x29, 0x4a, 0x66, 0x5c, 0x42, 0xc8, 0x8a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xd1,
	0x55, 0x09, 0x09, 0x70, 0x31, 0xe7, 0x16, 0xa7, 0x4b, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0x98, 0x4e, 0x6c, 0x51, 0x2c, 0xb9, 0x89, 0x99, 0x79, 0x49, 0x6c, 0x60, 0x8b, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x32, 0xa6, 0xfd, 0x8a, 0x8a, 0x00, 0x00, 0x00,
}
