// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExampleOneRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleOneRequest) Reset()         { *m = ExampleOneRequest{} }
func (m *ExampleOneRequest) String() string { return proto.CompactTextString(m) }
func (*ExampleOneRequest) ProtoMessage()    {}
func (*ExampleOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *ExampleOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleOneRequest.Unmarshal(m, b)
}
func (m *ExampleOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleOneRequest.Marshal(b, m, deterministic)
}
func (m *ExampleOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleOneRequest.Merge(m, src)
}
func (m *ExampleOneRequest) XXX_Size() int {
	return xxx_messageInfo_ExampleOneRequest.Size(m)
}
func (m *ExampleOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleOneRequest proto.InternalMessageInfo

func (m *ExampleOneRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ExampleOneResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleOneResponse) Reset()         { *m = ExampleOneResponse{} }
func (m *ExampleOneResponse) String() string { return proto.CompactTextString(m) }
func (*ExampleOneResponse) ProtoMessage()    {}
func (*ExampleOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *ExampleOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleOneResponse.Unmarshal(m, b)
}
func (m *ExampleOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleOneResponse.Marshal(b, m, deterministic)
}
func (m *ExampleOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleOneResponse.Merge(m, src)
}
func (m *ExampleOneResponse) XXX_Size() int {
	return xxx_messageInfo_ExampleOneResponse.Size(m)
}
func (m *ExampleOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleOneResponse proto.InternalMessageInfo

func (m *ExampleOneResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ExampleOneResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ExampleOneRequest)(nil), "s12.example.ExampleOneRequest")
	proto.RegisterType((*ExampleOneResponse)(nil), "s12.example.ExampleOneResponse")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2e, 0x36, 0x34, 0xd2, 0x83,
	0x0a, 0x49, 0xf1, 0x41, 0x19, 0x46, 0x10, 0x49, 0x25, 0x55, 0x2e, 0x41, 0x57, 0x88, 0x88, 0x7f,
	0x5e, 0x6a, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x00, 0x17, 0x73, 0x6e, 0x71, 0xba,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x88, 0xa9, 0x64, 0xc6, 0x25, 0x84, 0xac, 0xac, 0xb8,
	0x20, 0x3f, 0xaf, 0x38, 0x55, 0x88, 0x8f, 0x8b, 0x29, 0x33, 0x05, 0xaa, 0x8c, 0x29, 0x33, 0x05,
	0xa6, 0x8f, 0x09, 0xae, 0xcf, 0x68, 0x1d, 0x23, 0x17, 0x1f, 0x54, 0x63, 0x70, 0x6a, 0x51, 0x59,
	0x66, 0x72, 0xaa, 0x90, 0x2f, 0x17, 0x17, 0xc2, 0x28, 0x21, 0x39, 0x3d, 0x24, 0xd7, 0xe9, 0x61,
	0x38, 0x45, 0x4a, 0x1e, 0xa7, 0x3c, 0xd4, 0x0d, 0x08, 0xe3, 0x42, 0xca, 0xf3, 0xb1, 0x1b, 0x17,
	0x52, 0x9e, 0x8f, 0xd7, 0x38, 0xb0, 0x3c, 0xc4, 0x38, 0x27, 0xb6, 0x28, 0x96, 0xdc, 0xc4, 0xcc,
	0xbc, 0x24, 0x36, 0x70, 0xf0, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x7e, 0xa9, 0x4b,
	0x4c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExampleServiceClient is the client API for ExampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleServiceClient interface {
	ExampleOne(ctx context.Context, in *ExampleOneRequest, opts ...grpc.CallOption) (*ExampleOneResponse, error)
	ExampleTwo(ctx context.Context, in *ExampleTwoRequest, opts ...grpc.CallOption) (*ExampleTwoResponse, error)
}

type exampleServiceClient struct {
	cc *grpc.ClientConn
}

func NewExampleServiceClient(cc *grpc.ClientConn) ExampleServiceClient {
	return &exampleServiceClient{cc}
}

func (c *exampleServiceClient) ExampleOne(ctx context.Context, in *ExampleOneRequest, opts ...grpc.CallOption) (*ExampleOneResponse, error) {
	out := new(ExampleOneResponse)
	err := c.cc.Invoke(ctx, "/s12.example.ExampleService/ExampleOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleServiceClient) ExampleTwo(ctx context.Context, in *ExampleTwoRequest, opts ...grpc.CallOption) (*ExampleTwoResponse, error) {
	out := new(ExampleTwoResponse)
	err := c.cc.Invoke(ctx, "/s12.example.ExampleService/ExampleTwo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleServiceServer is the server API for ExampleService service.
type ExampleServiceServer interface {
	ExampleOne(context.Context, *ExampleOneRequest) (*ExampleOneResponse, error)
	ExampleTwo(context.Context, *ExampleTwoRequest) (*ExampleTwoResponse, error)
}

// UnimplementedExampleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedExampleServiceServer struct {
}

func (*UnimplementedExampleServiceServer) ExampleOne(ctx context.Context, req *ExampleOneRequest) (*ExampleOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExampleOne not implemented")
}
func (*UnimplementedExampleServiceServer) ExampleTwo(ctx context.Context, req *ExampleTwoRequest) (*ExampleTwoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExampleTwo not implemented")
}

func RegisterExampleServiceServer(s *grpc.Server, srv ExampleServiceServer) {
	s.RegisterService(&_ExampleService_serviceDesc, srv)
}

func _ExampleService_ExampleOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).ExampleOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/s12.example.ExampleService/ExampleOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).ExampleOne(ctx, req.(*ExampleOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleService_ExampleTwo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleTwoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).ExampleTwo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/s12.example.ExampleService/ExampleTwo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).ExampleTwo(ctx, req.(*ExampleTwoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExampleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "s12.example.ExampleService",
	HandlerType: (*ExampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExampleOne",
			Handler:    _ExampleService_ExampleOne_Handler,
		},
		{
			MethodName: "ExampleTwo",
			Handler:    _ExampleService_ExampleTwo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}
